import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/layouts/navbar"
import Footer from "@/components/layouts/footer";
import  { Toaster } from 'react-hot-toast';
import CartContextProvider from "@/contexts/cartContext";
import WishlistContextProvider from "@/contexts/wishlistContext";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <SessionProviderWrapper>
        <CartContextProvider>
          <WishlistContextProvider>
            <Navbar/>
            {children}
          </WishlistContextProvider>
        </CartContextProvider>
      </SessionProviderWrapper>
        <Toaster/>
<Footer/>
      </body>
    </html>
  );
}
